name: Publish to TestPyPI

on:
  # Publish to TestPyPI when we push to master
  push:
    branches: [ master ]

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools build wheel twine
    - name: Build
      run: |
        python -m build --sdist --outdir dist/
    - name: Publish
      run: |
        python -m twine upload dist/* --verbose
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: $${ secrets.TEST_PYPI_API_SECRET }}
        TWINE_REPOSITORY: testpypi
